"""
Integration utilities for globtimpostprocessing refinement.

This module provides Phase 3 integration: local refinement of critical points
found by globtimcore using gradient-free local optimization.

# Architecture

Phase 3 implements a 2-stage optimization pipeline:
1. **Stage 1 (globtimcore)**: Find raw critical points using polynomial approximation
2. **Stage 2 (globtimpostprocessing)**: Refine critical points using local optimization

# Key Features

- **File-based interface**: Reads `critical_points_raw_deg_*.csv` from globtimcore
- **Gradient-free optimization**: Uses Nelder-Mead (ODE solvers incompatible with ForwardDiff)
- **Timeout handling**: Prevents hanging on stiff ODE problems (default 60s per point)
- **Error tracking**: Graceful handling of failed refinements
- **Performance metrics**: Tracks improvement factors and convergence rates

# Limitations

**ForwardDiff Incompatibility**: Dynamic_objectives uses ODE solvers which cannot
propagate ForwardDiff.Dual types. Therefore:
- Only gradient-free methods supported (Nelder-Mead, Powell's, etc.)
- No BFGS or gradient-based refinement

# Usage

```julia
using Dynamic_objectives

# Stage 1: Run globtimcore (in separate environment)
# ... creates critical_points_raw_deg_*.csv files

# Stage 2: Refine critical points
config = ode_refinement_config(
    max_time_per_point = 60.0,
    optimization_method = :nelder_mead
)

result = refine_experiment_results(
    "path/to/globtim/output",
    objective_function,
    config
)

# Access refined results
println("Best refined value: ", result[:best_refined_value])
println("Improvement: ", result[:mean_improvement], "x")
println("Convergence rate: ", result[:n_converged], "/", result[:n_raw])
```

See `examples/globtim_integration/run_full_pipeline.jl` for complete workflow.
"""

using LinearAlgebra
using CSV
using DataFrames
using Optim
using JSON

export RefinementConfig, ode_refinement_config, refine_experiment_results

"""
    RefinementConfig

Configuration for local refinement of critical points.

# Fields
- `max_time_per_point::Float64`: Maximum optimization time per point (seconds)
- `optimization_method::Symbol`: Local optimization method (:nelder_mead, :powell, etc.)
- `max_iterations::Int`: Maximum iterations for local optimizer
- `x_tol::Float64`: Convergence tolerance for parameter changes
- `f_tol::Float64`: Convergence tolerance for objective changes
- `distance_metric::Symbol`: Distance function for objectives (:L2, :L1)
- `verbose::Bool`: Print detailed refinement progress
"""
struct RefinementConfig
    max_time_per_point::Float64
    optimization_method::Symbol
    max_iterations::Int
    x_tol::Float64
    f_tol::Float64
    distance_metric::Symbol
    verbose::Bool
end

"""
    ode_refinement_config(; kwargs...)

Create refinement configuration optimized for ODE-based objectives.

# Keyword Arguments
- `max_time_per_point::Float64 = 60.0`: Timeout per point (prevents hanging on stiff ODEs)
- `optimization_method::Symbol = :nelder_mead`: Gradient-free method (ForwardDiff incompatible)
- `max_iterations::Int = 1000`: Maximum optimizer iterations
- `x_tol::Float64 = 1e-6`: Parameter convergence tolerance
- `f_tol::Float64 = 1e-6`: Objective convergence tolerance
- `distance_metric::Symbol = :L2`: Distance metric for objectives
- `verbose::Bool = true`: Print refinement progress

# Returns
- `RefinementConfig`: Configuration object for `refine_experiment_results()`

# Example
```julia
# Conservative settings for stiff ODEs
config = ode_refinement_config(
    max_time_per_point = 120.0,  # Longer timeout
    x_tol = 1e-4,                 # Looser tolerance
    verbose = true
)
```
"""
function ode_refinement_config(;
    max_time_per_point::Float64 = 60.0,
    optimization_method::Symbol = :nelder_mead,
    max_iterations::Int = 1000,
    x_tol::Float64 = 1e-6,
    f_tol::Float64 = 1e-6,
    distance_metric::Symbol = :L2,
    verbose::Bool = true
)
    return RefinementConfig(
        max_time_per_point,
        optimization_method,
        max_iterations,
        x_tol,
        f_tol,
        distance_metric,
        verbose
    )
end

"""
    refine_experiment_results(output_dir, objective, config)

Refine critical points from globtimcore using local optimization.

This function implements Phase 3 of the globtim integration pipeline. It reads
raw critical points from CSV files generated by globtimcore and refines them
using gradient-free local optimization.

# Arguments
- `output_dir::String`: Directory containing `critical_points_raw_deg_*.csv` files
- `objective::Function`: Objective function with signature `f(p::Vector{Float64}) -> Float64`
- `config::RefinementConfig`: Refinement configuration (use `ode_refinement_config()`)

# Returns
Dictionary with keys:
- `:n_raw`: Number of raw critical points processed
- `:n_converged`: Number successfully refined
- `:mean_improvement`: Average improvement factor (raw_value / refined_value)
- `:best_raw_value`: Best objective value before refinement
- `:best_refined_value`: Best objective value after refinement
- `:refined_points`: Vector of refined parameter estimates
- `:best_refined_idx`: Index of best refined point
- `:refinement_details`: Per-point refinement statistics
- `:output_files`: Paths to generated CSV/JSON files

# Output Files
Generated in `output_dir`:
- `critical_points_refined_deg_N.csv`: Refined critical points
- `refinement_comparison_deg_N.csv`: Side-by-side comparison (raw vs. refined)
- `refinement_summary.json`: Aggregate statistics and metadata

# Example
```julia
using Dynamic_objectives

# Create objective function
model, _, _, outputs = define_lotka_volterra_2D_model_v3_two_outputs()
p_true = [1.0, 0.5]
ic = [1.0, 0.5]

objective = make_error_distance(
    model, outputs, ic, p_true,
    [0.0, 20.0], 30,
    L2_norm, first, nothing;
    eval_timeout = 10.0
)

# Configure refinement
config = ode_refinement_config(max_time_per_point = 60.0)

# Refine results from globtimcore
result = refine_experiment_results(
    "results/lotka_volterra_2D",
    objective,
    config
)

println("Improvement: ", result[:mean_improvement], "x")
println("Best refined: ", result[:refined_points][result[:best_refined_idx]])
```

# Error Handling
- Timeouts: Points exceeding `max_time_per_point` are marked as failed
- ODE failures: Objective returning Inf/NaN triggers graceful skip
- Convergence failures: Non-converged points tracked separately
"""
function refine_experiment_results(
    output_dir::String,
    objective::Function,
    config::RefinementConfig
)
    if config.verbose
        println("\n" * "="^80)
        println("Starting Critical Point Refinement (Phase 3)")
        println("="^80)
        println("  Output directory: $output_dir")
        println("  Method: $(config.optimization_method)")
        println("  Timeout: $(config.max_time_per_point)s per point")
        println("="^80)
    end

    # Find all raw critical point files
    raw_files = filter(f -> occursin(r"critical_points.*deg_\d+\.csv", f), readdir(output_dir))

    if isempty(raw_files)
        error("No critical point CSV files found in $output_dir")
    end

    if config.verbose
        println("\nFound $(length(raw_files)) critical point file(s)")
    end

    # Storage for all results
    all_refined_points = []
    all_refinement_details = []
    best_refined_value = Inf
    best_refined_idx = -1
    best_raw_value = Inf

    # Process each degree file
    for raw_file in raw_files
        raw_path = joinpath(output_dir, raw_file)

        # Extract degree from filename
        degree_match = match(r"deg_(\d+)", raw_file)
        degree = degree_match !== nothing ? parse(Int, degree_match[1]) : 0

        if config.verbose
            println("\n" * "─"^60)
            println("Processing: $raw_file (degree $degree)")
            println("─"^60)
        end

        # Read raw critical points
        df = CSV.read(raw_path, DataFrame)
        n_raw = nrow(df)

        if config.verbose
            println("  Raw critical points: $n_raw")
        end

        # Extract parameter columns (all columns except point_id and objective_value)
        param_cols = filter(n -> !occursin("point_id", n) && !occursin("objective", n), names(df))
        dimension = length(param_cols)

        if config.verbose
            println("  Dimension: $dimension")
        end

        # Refine each critical point
        refined_data = []
        n_converged = 0
        n_timeout = 0
        n_failed = 0
        improvements = Float64[]

        for i in 1:n_raw
            # Extract initial point
            x0 = [df[i, col] for col in param_cols]
            raw_value = df[i, end]  # Last column is objective value

            # Track best raw value
            if raw_value < best_raw_value
                best_raw_value = raw_value
            end

            if config.verbose && n_raw > 1
                print("\r  Refining point $i/$n_raw... ")
                flush(stdout)
            end

            # Perform local refinement with timeout
            start_time = time()
            refined_point = copy(x0)
            refined_value = raw_value
            converged = false
            timed_out = false
            error_msg = ""

            try
                # Set up optimization with timeout monitoring
                result = optimize(
                    objective,
                    x0,
                    NelderMead(),
                    Optim.Options(
                        iterations = config.max_iterations,
                        x_tol = config.x_tol,
                        f_tol = config.f_tol,
                        show_trace = false,
                        time_limit = config.max_time_per_point
                    )
                )

                elapsed = time() - start_time

                # Check for timeout
                if elapsed >= config.max_time_per_point
                    timed_out = true
                    n_timeout += 1
                    error_msg = "timeout"
                else
                    refined_point = Optim.minimizer(result)
                    refined_value = Optim.minimum(result)
                    converged = Optim.converged(result)

                    if converged
                        n_converged += 1
                    else
                        n_failed += 1
                        error_msg = "no_convergence"
                    end
                end

            catch e
                elapsed = time() - start_time
                n_failed += 1
                error_msg = "error: $(typeof(e))"
            end

            # Compute improvement
            improvement = raw_value / refined_value
            if isfinite(improvement) && improvement > 0
                push!(improvements, improvement)
            end

            # Track best refined point
            if refined_value < best_refined_value
                best_refined_value = refined_value
                best_refined_idx = length(all_refined_points) + 1
            end

            # Store refined point
            push!(all_refined_points, refined_point)

            # Store refinement details
            push!(all_refinement_details, Dict(
                "degree" => degree,
                "point_id" => i,
                "raw_value" => raw_value,
                "refined_value" => refined_value,
                "improvement" => improvement,
                "converged" => converged,
                "timed_out" => timed_out,
                "error" => error_msg,
                "elapsed_time" => time() - start_time
            ))

            # Store for CSV output
            row_data = vcat([degree, i], refined_point, [refined_value, raw_value, improvement, converged])
            push!(refined_data, row_data)
        end

        if config.verbose && n_raw > 1
            println("\r  ✓ Refinement complete")
        end

        # Compute statistics
        convergence_rate = n_converged / n_raw * 100
        mean_improvement = isempty(improvements) ? 1.0 : mean(improvements)

        if config.verbose
            println("\n  Results:")
            println("    Converged: $n_converged/$n_raw ($(round(convergence_rate, digits=1))%)")
            println("    Timeouts: $n_timeout")
            println("    Failed: $n_failed")
            println("    Mean improvement: $(round(mean_improvement, digits=2))x")
            if !isempty(improvements)
                println("    Max improvement: $(round(maximum(improvements), digits=2))x")
            end
        end

        # Write refined critical points CSV
        refined_file = replace(raw_file, "raw" => "refined")
        refined_path = joinpath(output_dir, refined_file)

        col_names = vcat(["degree", "point_id"], ["p$i" for i in 1:dimension],
                        ["refined_value", "raw_value", "improvement", "converged"])
        refined_df = DataFrame(refined_data, col_names)
        CSV.write(refined_path, refined_df)

        # Write comparison CSV
        comparison_file = replace(raw_file, "critical_points" => "refinement_comparison")
        comparison_path = joinpath(output_dir, comparison_file)
        CSV.write(comparison_path, refined_df)

        if config.verbose
            println("\n  Output files:")
            println("    $(refined_file)")
            println("    $(comparison_file)")
        end
    end

    # Compute overall statistics
    n_total = length(all_refined_points)
    n_total_converged = count(d -> d["converged"], all_refinement_details)
    overall_improvements = [d["improvement"] for d in all_refinement_details if isfinite(d["improvement"])]
    mean_improvement = isempty(overall_improvements) ? 1.0 : mean(overall_improvements)

    # Summary
    if config.verbose
        println("\n" * "="^80)
        println("Refinement Complete")
        println("="^80)
        println("  Total points: $n_total")
        println("  Converged: $n_total_converged ($(round(100*n_total_converged/n_total, digits=1))%)")
        println("  Mean improvement: $(round(mean_improvement, digits=2))x")
        println("  Best raw value: $(round(best_raw_value, digits=6))")
        println("  Best refined value: $(round(best_refined_value, digits=6))")
        println("  Overall improvement: $(round(best_raw_value/best_refined_value, digits=2))x")
        println("="^80)
    end

    # Write summary JSON
    summary = Dict(
        "n_raw" => n_total,
        "n_converged" => n_total_converged,
        "convergence_rate" => n_total_converged / n_total,
        "mean_improvement" => mean_improvement,
        "best_raw_value" => best_raw_value,
        "best_refined_value" => best_refined_value,
        "overall_improvement" => best_raw_value / best_refined_value,
        "config" => Dict(
            "max_time_per_point" => config.max_time_per_point,
            "optimization_method" => string(config.optimization_method),
            "max_iterations" => config.max_iterations,
            "x_tol" => config.x_tol,
            "f_tol" => config.f_tol
        ),
        "refinement_details" => all_refinement_details
    )

    summary_path = joinpath(output_dir, "refinement_summary.json")
    open(summary_path, "w") do io
        JSON.print(io, summary, 2)
    end

    # Return structured results
    return Dict(
        :n_raw => n_total,
        :n_converged => n_total_converged,
        :mean_improvement => mean_improvement,
        :best_raw_value => best_raw_value,
        :best_refined_value => best_refined_value,
        :refined_points => all_refined_points,
        :best_refined_idx => best_refined_idx,
        :refinement_details => all_refinement_details,
        :output_files => [summary_path]
    )
end
